# Generated by Django 5.0.6 on 2024-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subverbo',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
