# Generated by Django 5.0.6 on 2024-06-11 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subverbo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='subverbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_story', to='api.subverbo'),
        ),
    ]
