# Generated by Django 5.0.6 on 2024-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_text_alter_story_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
